name: Docker build

on:
  repository_dispatch:
    types: [update-event]
  workflow_dispatch:
jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        
      - name: Echo client-payload values
        run: |
          echo "Ref: ${{ github.event.client_payload.ref }}"
          echo "SHA: ${{ github.event.client_payload.sha }}"
          echo "Datasource: ${{ github.event.client_payload.datasource }}"
          echo "Release number: ${{ github.event.client_payload.version }}"
          echo "URL: ${{ github.event.client_payload.url }}"
          echo "Processed data: ${{ github.event.client_payload.processed_data }}"
